/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiSaveKeyRouteImport } from './routes/api/save-key'
import { Route as ApiOpenrouterRouteImport } from './routes/api/openrouter'
import { Route as ApiOpenaiRouteImport } from './routes/api/openai'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSaveKeyRoute = ApiSaveKeyRouteImport.update({
  id: '/api/save-key',
  path: '/api/save-key',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOpenrouterRoute = ApiOpenrouterRouteImport.update({
  id: '/api/openrouter',
  path: '/api/openrouter',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOpenaiRoute = ApiOpenaiRouteImport.update({
  id: '/api/openai',
  path: '/api/openai',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/openai': typeof ApiOpenaiRoute
  '/api/openrouter': typeof ApiOpenrouterRoute
  '/api/save-key': typeof ApiSaveKeyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/openai': typeof ApiOpenaiRoute
  '/api/openrouter': typeof ApiOpenrouterRoute
  '/api/save-key': typeof ApiSaveKeyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/openai': typeof ApiOpenaiRoute
  '/api/openrouter': typeof ApiOpenrouterRoute
  '/api/save-key': typeof ApiSaveKeyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/openai' | '/api/openrouter' | '/api/save-key'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/openai' | '/api/openrouter' | '/api/save-key'
  id: '__root__' | '/' | '/api/openai' | '/api/openrouter' | '/api/save-key'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiOpenaiRoute: typeof ApiOpenaiRoute
  ApiOpenrouterRoute: typeof ApiOpenrouterRoute
  ApiSaveKeyRoute: typeof ApiSaveKeyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/save-key': {
      id: '/api/save-key'
      path: '/api/save-key'
      fullPath: '/api/save-key'
      preLoaderRoute: typeof ApiSaveKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/openrouter': {
      id: '/api/openrouter'
      path: '/api/openrouter'
      fullPath: '/api/openrouter'
      preLoaderRoute: typeof ApiOpenrouterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/openai': {
      id: '/api/openai'
      path: '/api/openai'
      fullPath: '/api/openai'
      preLoaderRoute: typeof ApiOpenaiRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiOpenaiRoute: ApiOpenaiRoute,
  ApiOpenrouterRoute: ApiOpenrouterRoute,
  ApiSaveKeyRoute: ApiSaveKeyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
